export interface ToolConfig {
  slug: string
  category: string
  nameKey: string
  descKey: string
  icon: string
}

export const tools: ToolConfig[] = [
  {
    slug: 'json-formatter',
    category: 'dev',
    nameKey: 'tool_json',
    descKey: 'tool_json_desc',
    icon: 'braces',
  },
  {
    slug: 'qr-code-generator',
    category: 'dev',
    nameKey: 'tool_qr',
    descKey: 'tool_qr_desc',
    icon: 'qr-code',
  },
  {
    slug: 'jwt-decoder',
    category: 'dev',
    nameKey: 'tool_jwt',
    descKey: 'tool_jwt_desc',
    icon: 'key-round',
  },
  {
    slug: 'cron-expression-generator',
    category: 'dev',
    nameKey: 'tool_cron',
    descKey: 'tool_cron_desc',
    icon: 'clock',
  },
  {
    slug: 'timestamp-converter',
    category: 'dev',
    nameKey: 'tool_timestamp',
    descKey: 'tool_timestamp_desc',
    icon: 'calendar-clock',
  },
  {
    slug: 'chinese-converter',
    category: 'text',
    nameKey: 'tool_chinese',
    descKey: 'tool_chinese_desc',
    icon: 'languages',
  },
  {
    slug: 'unicode-converter',
    category: 'dev',
    nameKey: 'tool_unicode',
    descKey: 'tool_unicode_desc',
    icon: 'binary',
  },
  {
    slug: 'mortgage-calculator',
    category: 'finance',
    nameKey: 'tool_mortgage',
    descKey: 'tool_mortgage_desc',
    icon: 'house',
  },
  {
    slug: 'compound-interest-calculator',
    category: 'finance',
    nameKey: 'tool_compound',
    descKey: 'tool_compound_desc',
    icon: 'trending-up',
  },
  {
    slug: 'loan-calculator',
    category: 'finance',
    nameKey: 'tool_loan',
    descKey: 'tool_loan_desc',
    icon: 'banknote',
  },
  {
    slug: 'credit-card-calculator',
    category: 'finance',
    nameKey: 'tool_creditcard',
    descKey: 'tool_creditcard_desc',
    icon: 'credit-card',
  },
  {
    slug: 'savings-calculator',
    category: 'finance',
    nameKey: 'tool_savings',
    descKey: 'tool_savings_desc',
    icon: 'piggy-bank',
  },
  {
    slug: 'roi-calculator',
    category: 'finance',
    nameKey: 'tool_roi',
    descKey: 'tool_roi_desc',
    icon: 'percent',
  },
  {
    slug: 'retirement-calculator',
    category: 'finance',
    nameKey: 'tool_retirement',
    descKey: 'tool_retirement_desc',
    icon: 'umbrella',
  },
  {
    slug: 'tax-calculator',
    category: 'finance',
    nameKey: 'tool_tax',
    descKey: 'tool_tax_desc',
    icon: 'receipt',
  },
  {
    slug: 'bmi-calculator',
    category: 'health',
    nameKey: 'tool_bmi',
    descKey: 'tool_bmi_desc',
    icon: 'heart-pulse',
  },
  {
    slug: 'tdee-calculator',
    category: 'health',
    nameKey: 'tool_tdee',
    descKey: 'tool_tdee_desc',
    icon: 'flame',
  },
  {
    slug: 'due-date-calculator',
    category: 'health',
    nameKey: 'tool_duedate',
    descKey: 'tool_duedate_desc',
    icon: 'baby',
  },
  {
    slug: 'percentage-calculator',
    category: 'everyday',
    nameKey: 'tool_percentage',
    descKey: 'tool_percentage_desc',
    icon: 'calculator',
  },
  {
    slug: 'age-calculator',
    category: 'everyday',
    nameKey: 'tool_age',
    descKey: 'tool_age_desc',
    icon: 'cake',
  },
  {
    slug: 'password-generator',
    category: 'dev',
    nameKey: 'tool_password',
    descKey: 'tool_password_desc',
    icon: 'shield',
  },
  {
    slug: 'length-converter',
    category: 'units',
    nameKey: 'tool_length',
    descKey: 'tool_length_desc',
    icon: 'ruler',
  },
  {
    slug: 'weight-converter',
    category: 'units',
    nameKey: 'tool_weight',
    descKey: 'tool_weight_desc',
    icon: 'weight',
  },
  {
    slug: 'temperature-converter',
    category: 'units',
    nameKey: 'tool_temperature',
    descKey: 'tool_temperature_desc',
    icon: 'thermometer',
  },
  {
    slug: 'area-converter',
    category: 'units',
    nameKey: 'tool_area',
    descKey: 'tool_area_desc',
    icon: 'square',
  },
  {
    slug: 'volume-converter',
    category: 'units',
    nameKey: 'tool_volume',
    descKey: 'tool_volume_desc',
    icon: 'beaker',
  },
  {
    slug: 'speed-converter',
    category: 'units',
    nameKey: 'tool_speed',
    descKey: 'tool_speed_desc',
    icon: 'gauge',
  },
  {
    slug: 'data-size-converter',
    category: 'units',
    nameKey: 'tool_datasize',
    descKey: 'tool_datasize_desc',
    icon: 'hard-drive',
  },
  {
    slug: 'time-converter',
    category: 'units',
    nameKey: 'tool_timeunit',
    descKey: 'tool_timeunit_desc',
    icon: 'timer',
  },
  { slug: 'discount-calculator', category: 'everyday', nameKey: 'tool_discount', descKey: 'tool_discount_desc', icon: 'tag' },
  { slug: 'tip-calculator', category: 'everyday', nameKey: 'tool_tip', descKey: 'tool_tip_desc', icon: 'receipt' },
  { slug: 'body-fat-calculator', category: 'health', nameKey: 'tool_bodyfat', descKey: 'tool_bodyfat_desc', icon: 'activity' },
  { slug: 'calorie-calculator', category: 'health', nameKey: 'tool_calorie', descKey: 'tool_calorie_desc', icon: 'apple' },
  { slug: 'heart-rate-calculator', category: 'health', nameKey: 'tool_heartrate', descKey: 'tool_heartrate_desc', icon: 'heart' },
  { slug: 'word-counter', category: 'text', nameKey: 'tool_wordcount', descKey: 'tool_wordcount_desc', icon: 'file-text' },
  { slug: 'case-converter', category: 'text', nameKey: 'tool_caseconvert', descKey: 'tool_caseconvert_desc', icon: 'type' },
  { slug: 'remove-duplicates', category: 'text', nameKey: 'tool_removedupes', descKey: 'tool_removedupes_desc', icon: 'filter' },
  { slug: 'lorem-ipsum-generator', category: 'text', nameKey: 'tool_loremipsum', descKey: 'tool_loremipsum_desc', icon: 'align-left' },
  { slug: 'diff-checker', category: 'text', nameKey: 'tool_diff', descKey: 'tool_diff_desc', icon: 'columns' },
  { slug: 'text-to-speech', category: 'text', nameKey: 'tool_tts', descKey: 'tool_tts_desc', icon: 'volume-2' },
  { slug: 'countdown-timer', category: 'everyday', nameKey: 'tool_countdown', descKey: 'tool_countdown_desc', icon: 'hourglass' },
  { slug: 'stopwatch', category: 'everyday', nameKey: 'tool_stopwatch', descKey: 'tool_stopwatch_desc', icon: 'timer' },
  { slug: 'random-number-generator', category: 'everyday', nameKey: 'tool_randomnum', descKey: 'tool_randomnum_desc', icon: 'dice-5' },
  { slug: 'random-picker', category: 'everyday', nameKey: 'tool_randompick', descKey: 'tool_randompick_desc', icon: 'shuffle' },
  { slug: 'date-calculator', category: 'everyday', nameKey: 'tool_datecalc', descKey: 'tool_datecalc_desc', icon: 'calendar' },
  { slug: 'color-converter', category: 'dev', nameKey: 'tool_color', descKey: 'tool_color_desc', icon: 'palette' },
  { slug: 'base64-encoder-decoder', category: 'dev', nameKey: 'tool_base64', descKey: 'tool_base64_desc', icon: 'file-code' },
  { slug: 'url-encoder-decoder', category: 'dev', nameKey: 'tool_urlencode', descKey: 'tool_urlencode_desc', icon: 'link' },
  { slug: 'hash-generator', category: 'dev', nameKey: 'tool_hash', descKey: 'tool_hash_desc', icon: 'fingerprint' },
  { slug: 'markdown-preview', category: 'dev', nameKey: 'tool_markdown', descKey: 'tool_markdown_desc', icon: 'file-text' },
  { slug: 'regex-tester', category: 'dev', nameKey: 'tool_regex', descKey: 'tool_regex_desc', icon: 'search' },
  { slug: 'yaml-json-converter', category: 'dev', nameKey: 'tool_yamljson', descKey: 'tool_yamljson_desc', icon: 'file-json' },
  { slug: 'csv-json-converter', category: 'dev', nameKey: 'tool_csvjson', descKey: 'tool_csvjson_desc', icon: 'table' },
  { slug: 'image-compressor', category: 'image', nameKey: 'tool_imagecompress', descKey: 'tool_imagecompress_desc', icon: 'image-down' },
  { slug: 'image-converter', category: 'image', nameKey: 'tool_imageconvert', descKey: 'tool_imageconvert_desc', icon: 'image' },
  { slug: 'image-cropper', category: 'image', nameKey: 'tool_imagecrop', descKey: 'tool_imagecrop_desc', icon: 'crop' },
  { slug: 'pdf-tools', category: 'image', nameKey: 'tool_pdftools', descKey: 'tool_pdftools_desc', icon: 'file' },
  { slug: 'image-to-pdf', category: 'image', nameKey: 'tool_image2pdf', descKey: 'tool_image2pdf_desc', icon: 'file-image' },
  { slug: 'utm-builder', category: 'dev', nameKey: 'tool_utm', descKey: 'tool_utm_desc', icon: 'link-2' },
  { slug: 'open-graph-preview', category: 'dev', nameKey: 'tool_ogpreview', descKey: 'tool_ogpreview_desc', icon: 'eye' },
  { slug: 'social-media-counter', category: 'text', nameKey: 'tool_socialcount', descKey: 'tool_socialcount_desc', icon: 'message-square' },
  { slug: 'emoji-search', category: 'text', nameKey: 'tool_emoji', descKey: 'tool_emoji_desc', icon: 'smile' },
  { slug: 'meta-tag-generator', category: 'dev', nameKey: 'tool_metatag', descKey: 'tool_metatag_desc', icon: 'code' },
]

export const categories = [
  { key: 'dev', labelKey: 'cat_dev' },
  { key: 'finance', labelKey: 'cat_finance' },
  { key: 'health', labelKey: 'cat_health' },
  { key: 'image', labelKey: 'cat_image' },
  { key: 'text', labelKey: 'cat_text' },
  { key: 'units', labelKey: 'cat_units' },
  { key: 'everyday', labelKey: 'cat_everyday' },
] as const
