import {
  Braces,
  QrCode,
  KeyRound,
  Clock,
  CalendarClock,
  Languages,
  Binary,
  House,
  TrendingUp,
  Banknote,
  CreditCard,
  PiggyBank,
  Percent,
  Umbrella,
  HeartPulse,
  Flame,
  Baby,
  Calculator,
  Cake,
  Shield,
  Ruler,
  Weight,
  Thermometer,
  Square,
  Beaker,
  Gauge,
  HardDrive,
  Timer,
  type LucideProps,
} from 'lucide-react'

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  braces: Braces,
  'qr-code': QrCode,
  'key-round': KeyRound,
  clock: Clock,
  'calendar-clock': CalendarClock,
  languages: Languages,
  binary: Binary,
  house: House,
  'trending-up': TrendingUp,
  banknote: Banknote,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  percent: Percent,
  umbrella: Umbrella,
  'heart-pulse': HeartPulse,
  flame: Flame,
  baby: Baby,
  calculator: Calculator,
  cake: Cake,
  shield: Shield,
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  square: Square,
  beaker: Beaker,
  gauge: Gauge,
  'hard-drive': HardDrive,
  timer: Timer,
}

export default function ToolIcon({ name, size = 28 }: { name: string; size?: number }) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon size={size} />
}
