import {
  Braces,
  QrCode,
  KeyRound,
  Clock,
  CalendarClock,
  Languages,
  Binary,
  House,
  TrendingUp,
  Banknote,
  CreditCard,
  PiggyBank,
  Percent,
  Umbrella,
  HeartPulse,
  Flame,
  Baby,
  Calculator,
  Cake,
  Shield,
  Ruler,
  Weight,
  Thermometer,
  Square,
  Beaker,
  Gauge,
  HardDrive,
  Timer,
  Tag,
  Receipt,
  Activity,
  Apple,
  Heart,
  FileText,
  Type,
  Filter,
  AlignLeft,
  Columns,
  Volume2,
  Hourglass,
  Dice5,
  Shuffle,
  Calendar,
  Palette,
  FileCode,
  Link,
  Fingerprint,
  Search,
  FileJson,
  Table,
  ImageDown,
  Image,
  Crop,
  File,
  FileImage,
  Link2,
  Eye,
  MessageSquare,
  Smile,
  Code,
  // New icons for new tools
  Scan,
  Paintbrush,
  Scaling,
  AppWindow,
  FileType,
  CodeXml,
  Blend,
  Globe,
  Minimize2,
  Maximize2,
  Database,
  TextCursorInput,
  Info,
  Lock,
  MonitorSmartphone,
  FileCode2,
  Layers,
  Circle,
  Sparkles,
  Scissors,
  Layout,
  Grid3x3,
  ScanBarcode,
  PenTool,
  Stamp,
  AlarmClock,
  ReceiptText,
  ShieldCheck,
  Key,
  Hash,
  Ticket,
  // Wave 3 icons
  Notebook,
  Keyboard,
  Wand2,
  Repeat,
  Wifi,
  Radio,
  ListOrdered,
  Frame,
  GraduationCap,
  Zap,
  Fuel,
  BarChart3,
  PenLine,
  Video,
  Terminal,
  Network,
  FolderSearch,
  EyeOff,
  Heading,
  FileOutput,
  ImagePlus,
  Footprints,
  BatteryCharging,
  ArrowDownUp,
  BookOpen,
  FastForward,
  type LucideProps,
} from 'lucide-react'

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  braces: Braces,
  'qr-code': QrCode,
  'key-round': KeyRound,
  clock: Clock,
  'calendar-clock': CalendarClock,
  languages: Languages,
  binary: Binary,
  house: House,
  'trending-up': TrendingUp,
  banknote: Banknote,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  percent: Percent,
  umbrella: Umbrella,
  'heart-pulse': HeartPulse,
  flame: Flame,
  baby: Baby,
  calculator: Calculator,
  cake: Cake,
  shield: Shield,
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  square: Square,
  beaker: Beaker,
  gauge: Gauge,
  'hard-drive': HardDrive,
  timer: Timer,
  tag: Tag,
  receipt: Receipt,
  activity: Activity,
  apple: Apple,
  heart: Heart,
  'file-text': FileText,
  type: Type,
  filter: Filter,
  'align-left': AlignLeft,
  columns: Columns,
  'volume-2': Volume2,
  hourglass: Hourglass,
  'dice-5': Dice5,
  shuffle: Shuffle,
  calendar: Calendar,
  palette: Palette,
  'file-code': FileCode,
  link: Link,
  fingerprint: Fingerprint,
  search: Search,
  'file-json': FileJson,
  table: Table,
  'image-down': ImageDown,
  image: Image,
  crop: Crop,
  file: File,
  'file-image': FileImage,
  'link-2': Link2,
  eye: Eye,
  'message-square': MessageSquare,
  smile: Smile,
  code: Code,
  // New icons
  scan: Scan,
  paintbrush: Paintbrush,
  scaling: Scaling,
  'app-window': AppWindow,
  'file-type': FileType,
  'code-xml': CodeXml,
  blend: Blend,
  globe: Globe,
  'minimize-2': Minimize2,
  'maximize-2': Maximize2,
  database: Database,
  'text-cursor-input': TextCursorInput,
  info: Info,
  lock: Lock,
  'monitor-smartphone': MonitorSmartphone,
  'file-code-2': FileCode2,
  layers: Layers,
  circle: Circle,
  sparkles: Sparkles,
  scissors: Scissors,
  layout: Layout,
  'grid-3x3': Grid3x3,
  'scan-barcode': ScanBarcode,
  'pen-tool': PenTool,
  stamp: Stamp,
  'alarm-clock': AlarmClock,
  'receipt-text': ReceiptText,
  'shield-check': ShieldCheck,
  key: Key,
  hash: Hash,
  ticket: Ticket,
  // Wave 3
  notebook: Notebook,
  keyboard: Keyboard,
  'wand-2': Wand2,
  repeat: Repeat,
  wifi: Wifi,
  radio: Radio,
  'list-ordered': ListOrdered,
  frame: Frame,
  'graduation-cap': GraduationCap,
  zap: Zap,
  fuel: Fuel,
  'bar-chart-3': BarChart3,
  'pen-line': PenLine,
  video: Video,
  terminal: Terminal,
  network: Network,
  'folder-search': FolderSearch,
  'eye-off': EyeOff,
  heading: Heading,
  'file-output': FileOutput,
  'image-plus': ImagePlus,
  footprints: Footprints,
  'battery-charging': BatteryCharging,
  'arrow-down-up': ArrowDownUp,
  'book-open': BookOpen,
  'fast-forward': FastForward,
}

export default function ToolIcon({ name, size = 28 }: { name: string; size?: number }) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon size={size} />
}
