import {
  Braces,
  QrCode,
  KeyRound,
  Clock,
  CalendarClock,
  Languages,
  Binary,
  House,
  TrendingUp,
  Banknote,
  CreditCard,
  PiggyBank,
  Percent,
  Umbrella,
  HeartPulse,
  Flame,
  Baby,
  Calculator,
  Cake,
  Shield,
  Ruler,
  Weight,
  Thermometer,
  Square,
  Beaker,
  Gauge,
  HardDrive,
  Timer,
  Tag,
  Receipt,
  Activity,
  Apple,
  Heart,
  FileText,
  Type,
  Filter,
  AlignLeft,
  Columns,
  Volume2,
  Hourglass,
  Dice5,
  Shuffle,
  Calendar,
  Palette,
  FileCode,
  Link,
  Fingerprint,
  Search,
  FileJson,
  Table,
  ImageDown,
  Image,
  Crop,
  File,
  FileImage,
  Link2,
  Eye,
  MessageSquare,
  Smile,
  Code,
  type LucideProps,
} from 'lucide-react'

const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  braces: Braces,
  'qr-code': QrCode,
  'key-round': KeyRound,
  clock: Clock,
  'calendar-clock': CalendarClock,
  languages: Languages,
  binary: Binary,
  house: House,
  'trending-up': TrendingUp,
  banknote: Banknote,
  'credit-card': CreditCard,
  'piggy-bank': PiggyBank,
  percent: Percent,
  umbrella: Umbrella,
  'heart-pulse': HeartPulse,
  flame: Flame,
  baby: Baby,
  calculator: Calculator,
  cake: Cake,
  shield: Shield,
  ruler: Ruler,
  weight: Weight,
  thermometer: Thermometer,
  square: Square,
  beaker: Beaker,
  gauge: Gauge,
  'hard-drive': HardDrive,
  timer: Timer,
  tag: Tag,
  receipt: Receipt,
  activity: Activity,
  apple: Apple,
  heart: Heart,
  'file-text': FileText,
  type: Type,
  filter: Filter,
  'align-left': AlignLeft,
  columns: Columns,
  'volume-2': Volume2,
  hourglass: Hourglass,
  'dice-5': Dice5,
  shuffle: Shuffle,
  calendar: Calendar,
  palette: Palette,
  'file-code': FileCode,
  link: Link,
  fingerprint: Fingerprint,
  search: Search,
  'file-json': FileJson,
  table: Table,
  'image-down': ImageDown,
  image: Image,
  crop: Crop,
  file: File,
  'file-image': FileImage,
  'link-2': Link2,
  eye: Eye,
  'message-square': MessageSquare,
  smile: Smile,
  code: Code,
}

export default function ToolIcon({ name, size = 28 }: { name: string; size?: number }) {
  const Icon = iconMap[name]
  if (!Icon) return null
  return <Icon size={size} />
}
